{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-futile.options
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/futile.options_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/futile.options/futile.options_{{ version }}.tar.gz
  sha256: 7a9cc974e09598077b242a1069f7fbf4fa7f85ffe25067f6c4c32314ef532570

build:
  merge_build_host: true  # [win]
  number: 1004
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('futile.options')"           # [not win]
    - "\"%R%\" -e \"library('futile.options')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=futile.options
  license: LGPL-3.0-only
  summary: A scoped options management framework. Used in other packages.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
