travis:
  secure:
    BINSTAR_TOKEN: nHzxeryOHivU/4hSOkKAYE2qG+vkScqcXfQh+Jz9HmycwUbnR92sBhlpdk0gMTjZDZoKh12jKIzpIX7/T1FGWZeLSWBcJMdJxU/OuNAcnxwiCqYY3sHF1RDA84tScukuhkaOMmmq1aGrJguaCQ4BhKRucnfyQ7uGU3yCwYx776QYPgU07syD5ze96dDhTlBY2cxLYUPv9jn95QOq26Fs//n9jRkUhbl1E2hyAlGyDSNnsUyIIzhQfOZDUo2A2e1yxpyaJeQNTe0ksDY538DwgSm7RlWFAFRN9mVtVow259NG/Nj2xeti4hsXfMIoIxp9LqtBLqYRPNx1OoXrPCjTwWateMLZKJyUJfC5k46CzdziPB/yJP4+LJeEG2r0O3w4XU083FIcffXBfeKDzVsI+8g+2018lRvsqvUYmVYlwemA6Fc2ZKke2dhkwuW3RMRJkYgqGUk1sDrLl7LZUxkXxBTEFX0Ie2QWuET/RY1Oi0adBo2WVbm0h+50Op1Wu5jg/P9FUZuODqkk3kTNtRj4wOBgLD2rIJ8wCC+WYLPnd489ykjBHYHBg5uK+GRjFgSFJWlMgpdXJOZ2CiLUVyigVVPUC24lnXtvY7s5B3QUTJxLTEyeyBL1taNB0jylqCvdlSp4E3O1qZRqXenCwwRb7fxhYVQeOByhtdLVVgreJUk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
