appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: hWu9gmJGV0BGydFfFNXnDHqD15Jy4Xg2OEQsWFPPPGxkYuM24TIIrGanZ9cVsShgXrqXV7M1KftwuCybYgVRyyE/laS4hFRDaerJOij0kTGbCmBUc6P2WUEheE5RMm3c5XfoRpx1TABN7oGAlhZXbju8ehBfJMcAnr5OyS/neZciJ4J7M06VwHlZnmMJgAmju0gRsnhWfoD51d2AW5ee20XStCI0YLqmUDYgonK5ycqzRmZdAtabQQZsoc3xa4KubddQ/tzyvwFcJzAMaX1tR6jDISVuyJ4H7gurHSfvk7TTcPkuIIxZApTYvZS1KEPEqWSZqa263W9Gc4YrnoS7bvMdQpHst4JAcxQzfj5cF/aUd4RKpc6He+X6FQveTVMpIbVHHWGrO+RtlRuiOprEav125S9XaujS5ehQqNiTQq9Hu6ZkBmuvB22V7BNXYmYBoWoMDYTdHBdtijafWdNS9tv631SY1f+weih+H3p3qpLiFweROF6Hnq2ntxUtRyvFf9KUEOqvRuWuShvjjylfyoS1FNBNKuN9/WqeGnZqWag9dyOkEc0L6kGkb1kVeXM8fSrHpZm2DIzeDXCOFaIvYz5ficUIcWy+GPJnXwS4lHXZWiINdEBWVQ9b3gl9LXTLn+xLSMBqx5L9GYGkT7JWagS0+ho4HkDLTfWZ3Hwx4/c=
